import {
    gql
} from "@apollo/client";

export const GET_MEMORY_APPOINTMENTS = gql `
query allAppointments($ids: [ID]){
    allAppointments(ids: $ids){
        appointmentId
        date
        timeStart
        timeEnd
        isDone
        center{
            id
            name
        }
        doctor{
            id
            lastName
            firstName
            patronymic
        }
        patient{
            id
            lastName
            firstName
            patronymic
            birthday
            age
        }
        manager{
            id
            lastName
            firstName
            patronymic
        }
        reasonAppeal
        complaints
        anamnesis
        objectively
        work
        home
        recommendations
        consultation
        comment
        nextAppointment
        analyzes{
            id
            text
            eventDate
            analyzeType{
            id
            name
            }
            status
            additionInformation
            analyzeImages{
            id
            rotation
            imageLink
            imageName
            image1600Link
            image300Link
            order
            }
        }
        appointmentImages{
            id
            order
            rotation
            imageLink
            image1600Link
            image300Link
            imageName
            photoType{
            id
            name
            }
        }
        chequeUnits{
            id
            price
            amount
            percentDiscount
            priceDiscount
            comment
            additionalComment
            totalPrice
            service{
            id
            name
            color
            parent{
                id
                name
            }
            }
        }
        activeCheques{
            id
            pId
            payed
            terminal{
            id
            name
            }
            prepayment
            totalChequePrice
            units{
            id
            price
            amount
            percentDiscount
            priceDiscount
            comment
            additionalComment
            totalPrice
            service{
                id
                name
                color
                parent{
                id
                name
                }
            }
            }
        }
    }
}
  `